_BASE_: "../Base-bagtricks.yml"

INPUT:
  SIZE_TRAIN: [320, 320]
  SIZE_TEST: [320, 320]

SOLVER:
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-4

  IMS_PER_BATCH: 48
  MAX_EPOCH: 120
  STEPS: [40, 70, 90]

  WARMUP_ITERS: 10
  FREEZE_ITERS: 10 

  CHECKPOINT_PERIOD: 20

DATASETS:
  NAMES: ("APM",)
  TESTS: ("APM",)

OUTPUT_DIR: "logs/apm/bagtricks_S50"
