_BASE_: "../Base-SBS.yml"

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True

SOLVER:
  OPT: "SGD"
  BASE_LR: 0.0001
  ETA_MIN_LR: 7.7e-5

  IMS_PER_BATCH: 32
  MAX_EPOCH: 60
  DELAY_EPOCHS: 30
  WARMUP_ITERS: 10
  FREEZE_ITERS: 10

  CHECKPOINT_PERIOD: 20

DATASETS:
  NAMES: ("APM_VeRi",)
  TESTS: ("APM_VeRi",)

TEST:
  EVAL_PERIOD: 20
  IMS_PER_BATCH: 64

OUTPUT_DIR: "logs/apm_veri/sbs_R50-ibn"
